### ISSUE TITLE
Command "describe:resource_model" is not defined.

### ISSUE THREAD

**Issue by matiaso** [MageTest/MageSpec#135]
Hello,

I got this error when I do describe:resource_model 'magespec_reviews/product' 

>  [Symfony\Component\Console\Exception\CommandNotFoundException]
>  Command "describe:resource_model" is not defined.
>  Did you mean one of these?
>      describe:controller
>      describe:helper
>      describe:block
>      describe:model
>      describe

I initially wanted to follow your example, but instead of proposing me to create the load method, I encountered this error:

> Mage_Core_Exception("Resource is not set.")

In case here is my composer.json:
`{
  "repositories": [
    {
      "type":"composer",
      "url":"https://packages.firegento.com"
    }
  ],
  "minimum-stability": "dev",
  "require": {
    "magento-hackathon/magento-composer-installer": "3.0.*",
    "aydin-hassan/magento-core-composer-installer": "~1.2",
    "firegento/magento": "1.9.2.0",
    "colinmollenhour/modman": "@stable",
    "magetest/magento-phpspec-extension": "~3.0"
  },
  "require-dev": {
    "magento-hackathon/composer-command-integrator": "*",
    "phpspec/phpspec": "~2.0"
  },
  "config": {
    "bin-dir": "html/bin",
    "autoload": {"psr-0": {"": "html"}},
    "secure-http": false
  },
  "extra": {
    "magento-root-dir": "html/",
    "magento-deploystrategy": "link",
    "magento-force": 1
  },
  "autoload": {
    "psr-0": {
      "": [
        "html/app",
        "html/app/code/local",
        "html/app/code/community",
        "html/app/code/core",
        "html/lib"
      ]
    }
  }
}`

Am I not getting the right version of MageSpec?

Thanks,

Matias

**Comment by shanethehat** [comment]
Resource model generation was removed in version 3.0.0. It was felt that these objects were so close to the framework that they were not something that should be specced.

**Comment by aphroz** [comment]
Ok, then we should change the readme and the example.
On May 21, 2016 2:12 AM, "Shane Auckland" <notifications@github.com> wrote:

Resource model generation was removed in version 3.0.0. It was felt that
these objects were so close to the framework that they were not something
that should be specced.

—
You are receiving this because you authored the thread.
Reply to this email directly or view it on GitHub
<https://github.com/MageTest/MageSpec/issues/135#issuecomment-220693793>

**Comment by shanethehat** [comment]
Quite right, 3.0.1 released.

**Comment by maxbaldanza** [comment]
`4.0.1` has been released which removes it from the readme 😄 
https://github.com/MageTest/MageSpec/releases/tag/4.0.1
