### ISSUE TITLE
PHP Fatal error:  Can't inherit abstract function PhpSpec\Locator\ResourceLocatorInterface::getPriority()

### ISSUE THREAD

**Issue by elvetemedve** [MageTest/MageSpec#137]
I get the following error when I run specs:

> PHP Fatal error:  Can't inherit abstract function PhpSpec\Locator\ResourceLocatorInterface::getPriority() (previously declared abstract in MageTest\PhpSpec\MagentoExtension\Locator\Magento\AbstractResourceLocator) in /vagrant/vendor/inviqa/worldpay-module/vendor/magetest/magento-phpspec-extension/src/MageTest/PhpSpec/MagentoExtension/Locator/Magento/ModelLocator.php on line 37

Environment:
- Php version 5.3.3
- PhpSpec version 2.3.0
- OS: CentOS release 6.7

If I remove the abstract method declaration, it works. See https://github.com/MageTest/MageSpec/blob/develop/src/MageTest/PhpSpec/MagentoExtension/Locator/Magento/AbstractResourceLocator.php#L216-L219

**Comment by maxbaldanza** [comment]
@elvetemedve I think this may have been a bug in PHP see: https://bugs.php.net/bug.php?id=43200
Are you still having issues?

**Comment by elvetemedve** [comment]
I haven't used MageSpec recently, so I don't know. But it seems to be a PHP bug indeed.

**Comment by maxbaldanza** [comment]
I'll close this issue for now as mentioned it doesn't seem like an issue in Magespec.
Feel free to open if it's still an issue
