### ISSUE TITLE
PHPSpec 3 support

### ISSUE THREAD

**Issue by Sam-Burns** [MageTest/MageSpec#138]
Hi guys,

I was wondering what the state of play is w.r.t. PHPSpec 3 support?  Is this working now, or is there anything left to be done that I could help with?

Thanks,

Sam

**Comment by ciaranmcnulty** [comment]
Note that PhpSpec 2 is going to be EOLed in the next few weeks @shanethehat @jamescowie

Do you need some more active maintainers?

**Comment by shanethehat** [comment]
I'm not sure what @jamescowie is up to these days, but I've not touched any PHP at all in well over a year and I'm definitely not involved with Magento! @ciaranmcnulty if you know anyone who could take this project over I'll happily add them.

**Comment by ciaranmcnulty** [comment]
@shanethehat well @ubick is using it on a project so would be interested, as would @maxbaldanza

**Comment by maxbaldanza** [comment]
I've submitted a PR to add support for phpspec 3.3 so would be good to get that looked at 👍 https://github.com/MageTest/MageSpec/pull/140

**Comment by shanethehat** [comment]
Done and done

**Comment by ciaranmcnulty** [comment]
Thanks!

**Comment by maxbaldanza** [comment]
New release adds PHPspec 3 support: https://github.com/MageTest/MageSpec/releases/tag/4.0.0
🎉

**Comment by Sam-Burns** [comment]
Thanks @maxbaldanza!  PhpSpec 4 is now in release candidate too ;-)  Anything I can do to help with another version?
