### ISSUE TITLE
Auto create new method in Block class not working

### ISSUE THREAD

**Issue by dwickstrom** [MageTest/MageSpec#66]
When i specify a new method in my specification,

``` php
function it_prompts_me_to_create_new_method()
{
    $this->foo()->shouldReturn(true);
}
```

and then run phpspec I should be prompted to create this method stub, right? Anyhow, this isn´t happening. Instead phpspec throws me a Varien_Exception like so:
![skarmbild_2014-08-29_13_42](https://cloud.githubusercontent.com/assets/1133233/4089802/02fa6a9c-2f73-11e4-8466-875f1e918499.png)

This is only happening with the Blocks. All the other types, controllers, models, helpers, resource models are working.
- I am on OSX 10.8.4
- Latest composer build
- Magento CE 1.9.0.1

Thanks

**Comment by maxbaldanza** [comment]
Closing this for now as I'm unable to re-create this on the latest version [4.0.0](https://github.com/MageTest/MageSpec/releases/tag/4.0.0)

Feel free to re-open if it is still an issue.
